version: '3'

services:
  clinic-web-database-container:
    image: clinic-web-database-image
    networks:
      - api-network
    environment:
      - DB_NAME=clinic_database
      - DB_USER=postgres
      - DB_PASSWORD=clinic_database_pass
      - DB_PORT=5432

  clinic-web-backend:
    image: clinic-web-server
    networks:
      - api-network
      - ui-network
    environment:
      - DB_HOST=clinic-web-database-container
      - BE_PORT=3000

  clinic-web-frontend:
    image: clinic-web-client
    networks:
      - ui-network
    environment:
      - REACT_APP_BACKEND_URL=http://clinic-web-backend:3000
      - FE_PORT=3001

networks:
  ui-network:
  api-network:
